### ISSUE TITLE
JunitXml plugin will not work on python versions < 2.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#40]
```
What steps will reproduce the problem?
1. Fix issue 39
2. run `unit2 -X` from a tree of the plugins branch


What is the expected output? What do you see instead?

An exception occurs:

Traceback (most recent call last):
  File "./unit2", line 7, in <module>
    main_()
  File "/home/aefalcon/src/unittest2.fix/unittest2/main.py", line 436, in main_
    TestProgram(module=None)
  File "/home/aefalcon/src/unittest2.fix/unittest2/main.py", line 152, in __init__
    self.runTests()
  File "/home/aefalcon/src/unittest2.fix/unittest2/main.py", line 428, in runTests
    self.result = testRunner.run(self.test)
  File "/home/aefalcon/src/unittest2.fix/unittest2/runner.py", line 360, in run
    hooks.stopTestRun(event)
  File "/home/aefalcon/src/unittest2.fix/unittest2/events.py", line 281, in __call__
    result = handler(event)
  File "/home/aefalcon/src/unittest2.fix/unittest2/plugins/junitxml.py", line 87, in stopTestRun
    output.write(self.path, encoding="utf-8", xml_declaration=True)
TypeError: write() got an unexpected keyword argument 'xml_declaration'


What version of the product are you using? On what operating system?

A version of 0.6.0.alpha patched for issue 39 with a base of changeset 
406:67d08c1573ea. Running on Ubuntu 10.10 with python 2.6.6


Please provide any additional information below.

the `xml_declaration` parameter to ElementTree.write does not exist in the 
python standard library's included version for versions 2.6 and less.  An 
updated version of elementtree may be installed but the plugin module stops 
looking for alternate locations to import from after succeeding in importing 
the original version from xml.etree.  I assume it should run on versions 
2.4-2.7 because of the README.
```

Original issue reported on code.google.com by `aefal...@gmail.com` on 17 Nov 2010 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
Plugins development will happen either in cpython or testtools depending on 
whether we come up with a stable or experimental API to start with.
```

Original comment by `robert.c...@gmail.com` on 7 Nov 2014 at 11:02
- Changed state: **WontFix**
